### ISSUE TITLE
exclude filter configuration not loaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andrepdo/findbugs-idea#10]
```
The $PROJECT_DIR$ not expanded correct when loading filters from files:


What steps will reproduce the problem?
1. select exclude filter from file within default project dir.
2. close idea
3. open idea - run findbugs.

What is the expected output?
running a configured findbugs session

 What do you see instead?
---------------------------------------------------------------------
ExcludeFilter configuration failed.: $PROJECT_DIR$/findBugs_excludeFilter.xml 
(No such file or directory)
java.io.FileNotFoundException: $PROJECT_DIR$/findBugs_excludeFilter.xml (No 
such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at edu.umd.cs.findbugs.filter.Filter.parse(Filter.java:188)
	at edu.umd.cs.findbugs.filter.Filter.<init>(Filter.java:125)
	at edu.umd.cs.findbugs.FindBugs.configureFilter(FindBugs.java:428)
	at edu.umd.cs.findbugs.FindBugs2.addFilter(FindBugs2.java:311)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsWorker.configureFilter(FindBugsWorker.java:269)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsWorker.createFindBugsEngine(FindBugsWorker.java:251)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsWorker.work(FindBugsWorker.java:176)
	at org.twodividedbyzero.idea.findbugs.actions.AnalyzeModuleFiles.initWorker(AnalyzeModuleFiles.java:158)
	at org.twodividedbyzero.idea.findbugs.actions.AnalyzeModuleFiles.actionPerformed(AnalyzeModuleFiles.java:78)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
	at java.awt.Component.processEvent(Component.java:6032)
	at java.awt.Container.processEvent(Container.java:2041)
	at java.awt.Component.dispatchEventImpl(Component.java:4630)
	at java.awt.Container.dispatchEventImpl(Container.java:2099)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
	at java.awt.Container.dispatchEventImpl(Container.java:2085)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:534)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:420)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
------------------------------------------------------------------




What version of the product are you using?  0.9.96
On what operating system?  Fedora
Idea version 11.1
```

Original issue reported on code.google.com by `ha.l...@gmail.com` on 7 May 2012 at 1:13

**Comment by entangledloops** [comment]
Upvote -- this is causing my extensive set of generated sources to be analyzed when I want them skipped.
