### ISSUE TITLE
AssertionError: classname com/bci/wsr/common/constants/UCMDocInfo should be dotted

### ISSUE THREAD

**Issue by mikeliucc** [andrepdo/findbugs-idea#106]
Hi,

I'm using this findbugs plugin in IntelliJ 15 EAP.  When running it against my project I got the following exception:

```
classname com/bci/wsr/common/constants/UCMDocInfo should be dotted
java.lang.AssertionError: classname com/bci/wsr/common/constants/UCMDocInfo should be dotted
	at edu.umd.cs.findbugs.PackageMemberAnnotation.<init>(PackageMemberAnnotation.java:76)
	at edu.umd.cs.findbugs.PackageMemberAnnotation.<init>(PackageMemberAnnotation.java:52)
	at edu.umd.cs.findbugs.FieldAnnotation.<init>(FieldAnnotation.java:90)
	at edu.umd.cs.findbugs.FieldAnnotation.<init>(FieldAnnotation.java:119)
	at edu.umd.cs.findbugs.BugInstance.addField(BugInstance.java:1401)
	at edu.umd.cs.findbugs.detect.TestASM.visitField(TestASM.java:83)
	at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:272)
	at org.objectweb.asm.ClassReader.readField(ClassReader.java:768)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:689)
	at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at edu.umd.cs.findbugs.asm.ClassNodeDetector.visitClass(ClassNodeDetector.java:72)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:167)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:58)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$1.run(FindBugsStarter.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:367)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

The class in question is an enum:
```
package com.bci.wsr.common.constants;

public enum UCMDocInfo {
	xBCILongTitle,
	xDescription,
	xKeywords
}
```

As a result, FindBug plugin reported on 0 error find (even though I know the project contains lots of errors).  I was wondering if you can look into fixing this?

Thanks,
Mike

**Comment by retomerz** [comment]
This error is caused by FindBugs (and not by the IDEA-Plugin).
You should report it here: https://github.com/findbugsproject/findbugs
Btw, I can not reproduce this error with your example enum.

Anyway, I have improved the error handling/feedback of the IDEA-Plugin:
The Analysis-Finished-Notification is now red and will indicate that an error occurred.
