### ISSUE TITLE
IndexOutOfBound in Filters settings

### ISSUE THREAD

**Issue by dr29bart** [andrepdo/findbugs-idea#111]
Filter Settings:
Removing 'Include filter files' when none filter is selected

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:734)
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.DefaultListModel.remove(DefaultListModel.java:496)
	at org.twodividedbyzero.idea.findbugs.gui.preferences.FilterConfiguration$3.actionPerformed(FilterConfiguration.java:189)

**Comment by retomerz** [comment]
Fixed in v0.9.998.
