### ISSUE TITLE
IOException: Error performing FindBugs analysis: IOException while scanning codebases

### ISSUE THREAD

**Issue by originalrusyn** [andrepdo/findbugs-idea#119]
IntelliJ IDEA 2016.2 EAP
Build #IU-162.74.16, built on May 13, 2016
IntelliJ IDEA EAP User
Expiration date: June 12, 2016
JRE: 1.8.0_76-release-b185 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

`
Error performing FindBugs analysis: IOException while scanning codebases
java.io.IOException: IOException while scanning codebases
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
	at org.twodividedbyzero.idea.findbugs.tasks.FindBugsTask.runFindBugs(FindBugsTask.java:104)
	at org.twodividedbyzero.idea.findbugs.tasks.FindBugsTask.run(FindBugsTask.java:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:132)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:333)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: edu.umd.cs.findbugs.classfile.InvalidClassFileFormatException: Invalid classfile format in /Users/m/git_repo/server/service/target/classes/m/n/server/support/http/mock/ITunesPostServiceMock.class
	at edu.umd.cs.findbugs.classfile.engine.ClassParser.readConstant(ClassParser.java:254)
	at edu.umd.cs.findbugs.classfile.engine.ClassParser.parse(ClassParser.java:110)
	at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBase.getClassDescriptor(SingleFileCodeBase.java:254)
	at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBaseEntry.getClassDescriptor(SingleFileCodeBaseEntry.java:76)
	at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:247)
	at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:779)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:217)
	... 15 more
`

**Comment by andrepdo** [comment]
Jdk compile time related Problem.

Caused by: edu.umd.cs.findbugs.classfile.InvalidClassFileFormatException: Invalid classfile format in /Users/m/git_repo/server/service/target/classes/m/n/server/support/http/mock/ITunesPostServiceMock.class
at edu.umd.cs.findbugs.classfile.engine.ClassParser.readConstant(ClassParser.java:254)
