### ISSUE TITLE
null

### ISSUE THREAD

**Issue by MatiasComercioITBA** [andrepdo/findbugs-idea#126]
null
java.lang.NullPointerException
	at org.twodividedbyzero.idea.findbugs.actions.ExportBugCollection.updateImpl(ExportBugCollection.java:86)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractAction.update(AbstractAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:120)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:304)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:642)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.isAvailable(GotoActionModel.java:637)
	at com.intellij.ide.util.gotoByName.GotoActionModel$MatchedValue.compareTo(GotoActionModel.java:202)
	at com.intellij.ide.util.gotoByName.GotoActionModel.compare(GotoActionModel.java:298)
	at java.util.TreeMap.put(TreeMap.java:552)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.TreeSet.addAll(TreeSet.java:312)
	at com.intellij.ide.util.gotoByName.GotoActionModel.sort(GotoActionModel.java:475)
	at com.intellij.ide.actions.GotoActionAction$2.filter(GotoActionAction.java:128)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread$2.run(ChooseByNameBase.java:1575)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2$1.run(ProgressIndicatorUtils.java:196)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by retomerz** [comment]
Fixed in v0.9.999. Please update the plugin.
Thank you for taking the time to submit the issue!
