### ISSUE TITLE
null

### ISSUE THREAD

**Issue by BorzdeG** [andrepdo/findbugs-idea#134]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 0.9.999
    IDEA: IntelliJ IDEA 2016.2 EAP
    IDEA-Build: IU-162.426.1, May 24, 2016
    JRE: 1.8.0_76-release-b205 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

null
java.lang.IllegalStateException
	at org.twodividedbyzero.idea.findbugs.common.EventDispatchThreadHelper.checkEDT(EventDispatchThreadHelper.java:59)
	at org.twodividedbyzero.idea.findbugs.gui.tree.model.BugInstanceNode.getPsiFile(BugInstanceNode.java:87)
	at org.twodividedbyzero.idea.findbugs.common.util.IdeaUtilImpl.findAnonymousClassPsiElement(IdeaUtilImpl.java:472)
	at org.twodividedbyzero.idea.findbugs.common.ExtendedProblemDescriptor.getPsiElement(ExtendedProblemDescriptor.java:138)
	at org.twodividedbyzero.idea.findbugs.gui.editor.BugsLineMarkerProvider.getLineMarkerInfo(BugsLineMarkerProvider.java:89)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:181)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:111)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

null
java.lang.IllegalStateException
	at org.twodividedbyzero.idea.findbugs.common.EventDispatchThreadHelper.checkEDT(EventDispatchThreadHelper.java:59)
	at org.twodividedbyzero.idea.findbugs.gui.tree.model.BugInstanceNode.getPsiFile(BugInstanceNode.java:87)
	at org.twodividedbyzero.idea.findbugs.common.util.IdeaUtilImpl.findAnonymousClassPsiElement(IdeaUtilImpl.java:472)
	at org.twodividedbyzero.idea.findbugs.common.ExtendedProblemDescriptor.getPsiElement(ExtendedProblemDescriptor.java:138)
	at org.twodividedbyzero.idea.findbugs.gui.editor.BugsLineMarkerProvider.getLineMarkerInfo(BugsLineMarkerProvider.java:89)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:181)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:111)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by retomerz** [comment]
This was fixed in v1.0.0 (#129).
Please update the plugin.
