### ISSUE TITLE
java.util.ConcurrentModificationException at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)

### ISSUE THREAD

**Issue by lure0xaos** [andrepdo/findbugs-idea#153]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.1.3
    IDEA-Build: IU-145.1617, June 3, 2016
    JRE: 1.8.0_92-b14 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.report(OverlyPermissiveMethod.java:219)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.finishPass(DetectorToDetector2Adapter.java:55)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1127)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:354)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:245)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:218)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$300(FindBugsStarter.java:74)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$3.run(FindBugsStarter.java:202)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
This is (or was) a bug in the fb-contrib plugin: http://fb-contrib.sourceforge.net/
Note that the new FindBugs-IDEA version 1.0.1 is bundled with the latest fb-contrib version v6.8.0.
You should update the FindBugs-IDEA plugin and report that error to fb-contrib if it happens again:
  https://sourceforge.net/p/fb-contrib/bugs/?source=navbar
