### ISSUE TITLE
No module found for jar://C:/dev/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.3.6.RELEASE/spring-boot-autoconfigure-1.3.6.RELEASE.jar!/org/springframework/boot/autoconfigure/session/SessionAutoConfiguration.class

### ISSUE THREAD

**Issue by lure0xaos** [andrepdo/findbugs-idea#157]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.2
    IDEA-Build: IU-162.1121.32, July 9, 2016
    JRE: 1.8.0_102-b14 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

java.lang.IllegalStateException: No module found for jar://C:/dev/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.3.6.RELEASE/spring-boot-autoconfigure-1.3.6.RELEASE.jar!/org/springframework/boot/autoconfigure/session/SessionAutoConfiguration.class
	at org.twodividedbyzero.idea.findbugs.core.FindBugsProjects.addFile(FindBugsProjects.java:87)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsProjects.addFiles(FindBugsProjects.java:73)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsCompileAfterHook$2.configure(FindBugsCompileAfterHook.java:214)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$4.compute(FindBugsStarter.java:231)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$4.compute(FindBugsStarter.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:870)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:228)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:218)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$300(FindBugsStarter.java:74)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$3.run(FindBugsStarter.java:202)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
This is fixed in version 1.0.1.
Please update the plugin.
