### ISSUE TITLE
org.dom4j.DocumentException: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory Nested exception: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory at org.dom4j.io.SAXReader.read(SAXReader.java:484)

### ISSUE THREAD

**Issue by Jendrik3** [andrepdo/findbugs-idea#161]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.2.1
    IDEA-Build: IC-162.1447.26, August 2, 2016
    JRE: 1.8.0_65-b17 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

`java.lang.ExceptionInInitializerError
	at org.twodividedbyzero.idea.findbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:80)
	at org.twodividedbyzero.idea.findbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:70)
	at org.twodividedbyzero.idea.findbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:303)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:297)
	at org.twodividedbyzero.idea.findbugs.gui.settings.GeneralTab.reset(GeneralTab.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.SettingsPane.reset(SettingsPane.java:168)
	at org.twodividedbyzero.idea.findbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.ModuleConfigurableImpl.reset(ModuleConfigurableImpl.java:56)
	at com.intellij.openapi.roots.ui.configuration.ModuleConfigurableWrapper.reset(ModuleConfigurableWrapper.java:70)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:62)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.createPanel(ModuleEditor.java:263)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:271)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:121)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:80)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:655)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:189)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:646)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:238)
	at com.intellij.openapi.ui.MasterDetailsComponent.reset(MasterDetailsComponent.java:374)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:264)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.reset(ModuleStructureConfigurable.java:341)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:363)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:124)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:80)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:101)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.<init>(ConfigurableEditor.java:110)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:52)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:215)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:194)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.showDialog(ModulesConfigurator.java:546)
	at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.openContentEntriesSettings(IdeaProjectSettingsService.java:89)
	at com.android.tools.idea.gradle.structure.editors.AndroidProjectSettingsService.openContentEntriesSettings(AndroidProjectSettingsService.java:159)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.navigate(PsiDirectoryNode.java:230)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:59)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Unable to load core plugin
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1477)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1427)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:154)
	... 88 more
Caused by: edu.umd.cs.findbugs.PluginException: Couldn't parse "jar:file:/C:/Users/Jendrik%20Wenke/.IdeaIC2016.2/config/plugins/FindBugs-IDEA-1.0.0/lib/findbugs.jar!/findbugs.xml" using org.dom4j.io.SAXReader
	at edu.umd.cs.findbugs.PluginLoader.getPluginDescriptor(PluginLoader.java:1182)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:653)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:400)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1473)
	... 90 more
Caused by: org.dom4j.DocumentException: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory Nested exception: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.dom4j.io.SAXReader.read(SAXReader.java:365)
	at edu.umd.cs.findbugs.PluginLoader.getPluginDescriptor(PluginLoader.java:1180)
	... 93 more
`

**Comment by retomerz** [comment]
Duplicate, see #154
