### ISSUE TITLE
ISE at common.EventDispatchThreadHelper.checkEDT(EventDispatchThreadHelper.java:59)

### ISSUE THREAD

**Issue by dimaLeah** [andrepdo/findbugs-idea#164]
The error was copied to the clipboard. Press Ctrl+V
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.1.3
    IDEA-Build: IU-145.1617, June 3, 2016
    JRE: 1.8.0_91-b15 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

java.lang.IllegalStateException
	at org.twodividedbyzero.idea.findbugs.common.EventDispatchThreadHelper.checkEDT(EventDispatchThreadHelper.java:59)
	at org.twodividedbyzero.idea.findbugs.gui.tree.model.BugInstanceNode.getPsiFile(BugInstanceNode.java:87)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.getSelectedPsiFile(BugTreeHelper.java:57)
	at org.twodividedbyzero.idea.findbugs.gui.tree.view.BugTree.getData(BugTree.java:149)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:81)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:69)
	at com.intellij.ide.impl.DataManagerImpl.access$300(DataManagerImpl.java:55)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.a(DataManagerImpl.java:398)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:369)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.a(GotoActionItemProvider.java:111)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:82)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.a(SearchEverywhereAction.java:1539)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.a(SearchEverywhereAction.java:1570)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1452)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
This is fixed in version 1.0.1 (issue #172).
Please update the plugin.
