### ISSUE TITLE
path in TreePath must be non null and not empty.

### ISSUE THREAD

**Issue by kiraXY** [andrepdo/findbugs-idea#166]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 15.0
    IDEA-Build: IU-143.381, October 30, 2015
    JRE: 1.8.0_40-release-b92 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.lang.IllegalArgumentException: path in TreePath must be non null and not empty.
	at javax.swing.tree.TreePath.<init>(TreePath.java:102)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.getPath(BugTreeHelper.java:214)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.gotoNode(BugTreeHelper.java:219)
	at org.twodividedbyzero.idea.findbugs.gui.tree.view.BugTree.gotoNode(BugTree.java:195)
	at org.twodividedbyzero.idea.findbugs.gui.editor.BugsLineMarkerProvider$BugGutterIconNavigationHandler.navigate(BugsLineMarkerProvider.java:165)
	at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:56)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.a(EditorGutterComponentImpl.java:1506)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1476)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:4263)
	at com.intellij.openapi.editor.impl.EditorImpl.access$12600(EditorImpl.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter$2.run(EditorImpl.java:5835)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.c(EditorImpl.java:5839)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5725)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6543)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2235)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2293)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2279)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by retomerz** [comment]
Duplicate, see issue #162
