### ISSUE TITLE
org.dom4j.DocumentException: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory Nested exception: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory at org.dom4j.io.SAXReader.read(SAXReader.java:484)

### ISSUE THREAD

**Issue by b0c1** [andrepdo/findbugs-idea#169]
The error was copied to the clipboard. Press Ctrl+V
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.2.3
    IDEA-Build: IU-162.1812.17, August 30, 2016
    JRE: 1.8.0_60-b27 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

java.lang.ExceptionInInitializerError
	at org.twodividedbyzero.idea.findbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:80)
	at org.twodividedbyzero.idea.findbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:70)
	at org.twodividedbyzero.idea.findbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:303)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:297)
	at org.twodividedbyzero.idea.findbugs.gui.settings.GeneralTab.reset(GeneralTab.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.SettingsPane.reset(SettingsPane.java:168)
	at org.twodividedbyzero.idea.findbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.ModuleConfigurableImpl.reset(ModuleConfigurableImpl.java:56)
	at com.intellij.openapi.roots.ui.configuration.ModuleConfigurableWrapper.reset(ModuleConfigurableWrapper.java:70)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:62)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.a(ModuleEditor.java:263)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:271)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:121)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:80)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:655)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:189)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:646)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:238)
	at com.intellij.openapi.ui.MasterDetailsComponent.reset(MasterDetailsComponent.java:374)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:264)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.reset(ModuleStructureConfigurable.java:341)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:363)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:124)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:80)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:101)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.<init>(ConfigurableEditor.java:110)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:52)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:215)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:194)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.showDialog(ModulesConfigurator.java:546)
	at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.openModuleSettings(IdeaProjectSettingsService.java:69)
	at com.android.tools.idea.gradle.structure.editors.AndroidProjectSettingsService.openModuleSettings(AndroidProjectSettingsService.java:94)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.navigate(PsiDirectoryNode.java:221)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.ide.actions.BaseNavigateToSourceAction.actionPerformed(BaseNavigateToSourceAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Unable to load core plugin
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1477)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1427)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:154)
	... 62 more
Caused by: edu.umd.cs.findbugs.PluginException: Couldn't parse "jar:file:/D:/Work/ide/.IntelliJIdea/config/plugins/FindBugs-IDEA-1.0.0/lib/findbugs.jar!/findbugs.xml" using org.dom4j.io.SAXReader
	at edu.umd.cs.findbugs.PluginLoader.getPluginDescriptor(PluginLoader.java:1182)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:653)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:400)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1473)
	... 64 more
Caused by: org.dom4j.DocumentException: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory Nested exception: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.dom4j.io.SAXReader.read(SAXReader.java:365)
	at edu.umd.cs.findbugs.PluginLoader.getPluginDescriptor(PluginLoader.java:1180)
	... 67 more

**Comment by retomerz** [comment]
Duplicate, see #154
