### ISSUE TITLE
Worker exited due to exception

### ISSUE THREAD

**Issue by meierval** [andrepdo/findbugs-idea#172]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.2.4
    IDEA-Build: IU-162.2032.8, September 9, 2016
    JRE: 1.8.0_112-release-b343 x86
    JVM: OpenJDK Server VM JetBrains s.r.o

Worker exited due to exception
java.lang.IllegalStateException
	at org.twodividedbyzero.idea.findbugs.common.EventDispatchThreadHelper.checkEDT(EventDispatchThreadHelper.java:59)
	at org.twodividedbyzero.idea.findbugs.gui.tree.model.BugInstanceNode.getPsiFile(BugInstanceNode.java:87)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.getSelectedPsiFile(BugTreeHelper.java:57)
	at org.twodividedbyzero.idea.findbugs.gui.tree.view.BugTree.getData(BugTree.java:149)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:81)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:69)
	at com.intellij.ide.impl.DataManagerImpl.access$300(DataManagerImpl.java:55)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.a(DataManagerImpl.java:393)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:364)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.c(GotoActionItemProvider.java:104)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:71)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1565)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1544)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1520)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1508)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:187)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:211)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
Steps to reproduce:
1. focus bug tree
2. start Search Everywhere
3. search something (f. e. type "goto")
-> ISE

**Comment by retomerz** [comment]
This is fixed in version 1.0.1.
Please update the plugin.
