### ISSUE TITLE
Module is null for file /Users/eklementev/work/bpms/bpms-service-rms/build/classes/main/bpms/service/rms/dto/link/LinkRegisterRequest.class

### ISSUE THREAD

**Issue by eklementev** [andrepdo/findbugs-idea#173]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.0
    IDEA: IntelliJ IDEA 2016.2.4
    IDEA-Build: IC-162.2032.8, September 9, 2016
    JRE: 1.8.0_112-release-b343 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

Module is null for file /Users/eklementev/work/bpms/bpms-service-rms/build/classes/main/bpms/service/rms/dto/link/LinkRegisterRequest.class
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.compiler.impl.OneProjectItemCompileScope.getAffectedModules(OneProjectItemCompileScope.java:74)
	at com.intellij.compiler.impl.CompositeScope.getAffectedModules(CompositeScope.java:88)
	at com.intellij.compiler.impl.CompileDriver.validateCompilerConfiguration(CompileDriver.java:623)
	at com.intellij.compiler.impl.CompileDriver.make(CompileDriver.java:114)
	at com.intellij.compiler.CompilerManagerImpl.make(CompilerManagerImpl.java:239)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$1.consume(FindBugsStarter.java:148)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$1.consume(FindBugsStarter.java:143)
	at org.twodividedbyzero.idea.findbugs.actions.AnalyzeCurrentEditorFile$1.createCompileScope(AnalyzeCurrentEditorFile.java:73)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.start(FindBugsStarter.java:143)
	at org.twodividedbyzero.idea.findbugs.actions.AnalyzeCurrentEditorFile.analyze(AnalyzeCurrentEditorFile.java:80)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractAnalyzeAction.actionPerformedImpl(AbstractAnalyzeAction.java:70)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractAction.actionPerformed(AbstractAction.java:75)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$2(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.IllegalStateException: No module found for file:///Users/eklementev/work/bpms/bpms-service-rms/build/classes/main/bpms/service/rms/dto/link/LinkRegisterRequest.class
	at org.twodividedbyzero.idea.findbugs.core.FindBugsProjects.addFile(FindBugsProjects.java:87)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsProjects.addFiles(FindBugsProjects.java:73)
	at org.twodividedbyzero.idea.findbugs.actions.AnalyzeCurrentEditorFile$1.configure(AnalyzeCurrentEditorFile.java:78)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$4.compute(FindBugsStarter.java:231)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$4.compute(FindBugsStarter.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:228)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:218)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$300(FindBugsStarter.java:74)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$3.run(FindBugsStarter.java:202)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
I'm not able to reproduce this issue.
Can you please provide more detailed info about your project structure ?
It seems that you are able do analyze the file "LinkRegisterRequest" but this does not belong to a module.
f.e. it would be interesting if you can compile this single file:
    a. Navigate to LinkRegisterRequest in IDEA
    b. Right-click -> Recompile "LinkRegisterRequest"
