### ISSUE TITLE
Out of bounds mutables in com.ideas.tetris.pacman.services.learning.LearningManagementService.copyLearningPropertiesAsync(Lcom/ideas/tetris/platform/common/job/JobStepContext;Lcom/ideas/tetris/platform/common/xml/schema/workcontext/v1/WorkContextType;Ljava/util/List;[Ljava/lang/String;Z)Ljava/util/concurrent/Future;

### ISSUE THREAD

**Issue by lanejo01** [andrepdo/findbugs-idea#194]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2016.2.5
    IDEA-Build: IU-162.2228.15, October 14, 2016
    JRE: 1.8.0_40-b25 amd64
    JVM: Java HotSpot(TM) 64-Bit Server VM Oracle Corporation

java.lang.AssertionError: Out of bounds mutables in com.ideas.tetris.pacman.services.learning.LearningManagementService.copyLearningPropertiesAsync(Lcom/ideas/tetris/platform/common/job/JobStepContext;Lcom/ideas/tetris/platform/common/xml/schema/workcontext/v1/WorkContextType;Ljava/util/List;[Ljava/lang/String;Z)Ljava/util/concurrent/Future;
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.transferTaintToMutables(TaintFrameModelingVisitor.java:571)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitInvoke(TaintFrameModelingVisitor.java:389)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitINVOKESTATIC(TaintFrameModelingVisitor.java:278)
	at org.apache.bcel.generic.INVOKESTATIC.accept(INVOKESTATIC.java:77)
	at edu.umd.cs.findbugs.ba.AbstractFrameModelingVisitor.analyzeInstruction(AbstractFrameModelingVisitor.java:84)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.analyzeInstruction(TaintFrameModelingVisitor.java:137)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:88)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:49)
	at edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.transfer(AbstractDataflowAnalysis.java:135)
	at edu.umd.cs.findbugs.ba.Dataflow.execute(Dataflow.java:376)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:166)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:52)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.getTaintDataFlow(AbstractTaintDetector.java:123)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.analyzeMethod(AbstractTaintDetector.java:91)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.visitClassContext(AbstractTaintDetector.java:76)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:355)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:244)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:217)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$300(FindBugsStarter.java:73)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$3.run(FindBugsStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retomerz** [comment]
@h3xstream User reports against FindBugs-IDEA 1.0.1 which is bundled with find-sec-bugs 1.5.0 (rev c51b8e5f15a2a73620bd48cbe74c3b599a0e31d0).

**Comment by h3xstream** [comment]
@lanejo01 
Please provide the code or an equivalent of **com.ideas.tetris.pacman.services.learning.LearningManagementService.copyLearningPropertiesAsync**.

Open an issue here : https://github.com/find-sec-bugs/find-sec-bugs/issues .. this is not related to the IDEA plugin.
