### ISSUE TITLE
Access is allowed from event dispatch thread only.

### ISSUE THREAD

**Issue by terheyden** [andrepdo/findbugs-idea#200]
All I did was install the FindBugs plugin, and restart.

Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@7b20f624 Current thread: Thread[JobScheduler FJ pool 1/4,4,main] 150614041 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.3#IU-163.7743.44 IDEA, eap:false, os:Mac OS X 10.11.6, java-version:JetBrains s.r.o 1.8.0_112-release-408-b2,6,main] 1431928025

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1010)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:999)
	at com.intellij.ui.content.impl.ContentManagerImpl.a(ContentManagerImpl.java:237)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeContent(ContentManagerImpl.java:210)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeAllContents(ContentManagerImpl.java:318)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:567)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:402)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel.getInstance(ToolWindowPanel.java:392)
	at org.twodividedbyzero.idea.findbugs.gui.editor.BugsLineMarkerProvider.getLineMarkerInfo(BugsLineMarkerProvider.java:73)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by retomerz** [comment]
You're using an old plugin version.
Please update the plugin to version 1.0.1

Via IDEA:
 https://www.jetbrains.com/help/idea/2016.2/installing-updating-and-uninstalling-repository-plugins.html#update
Or manually:
 https://plugins.jetbrains.com/plugin/download?pr=&updateId=29582
