### ISSUE TITLE
Wrong line: 157. Available lines count: 155

### ISSUE THREAD

**Issue by baflQA** [andrepdo/findbugs-idea#280]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2017.3
    IDEA-Build: IC-173.3727.127, November 27, 2017
    JRE: 1.8.0_152-release-1024-b6 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.lang.IndexOutOfBoundsException: Wrong line: 157. Available lines count: 155
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:204)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:189)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:902)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.createEditor(BugTreePanel.java:216)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.setPreview(BugTreePanel.java:172)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.setPreviewEnabled(BugTreePanel.java:155)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel.setPreviewEnabled(ToolWindowPanel.java:237)
	at org.twodividedbyzero.idea.findbugs.actions.PreviewSelectBugInstance.setSelectedImpl(PreviewSelectBugInstance.java:70)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractToggleAction.setSelected(AbstractToggleAction.java:163)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:274)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by retomerz** [comment]
Duplicate see #163.
Will be fixed in version 1.0.2
