### ISSUE TITLE
Incorrect offsets: startOffset=2966, endOffset=87508, text length=83881

### ISSUE THREAD

**Issue by TicaTac** [andrepdo/findbugs-idea#281]
The error was copied to the clipboard. Press Command+V

**Comment by TicaTac** [comment]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2017.3
    IDEA-Build: IU-173.3727.127, November 27, 2017
    JRE: 1.8.0_152-release-1024-b6 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.lang.Throwable: Incorrect offsets: startOffset=2966, endOffset=87508, text length=83881
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:426)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:241)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:363)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.createEditor(BugTreePanel.java:214)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.setPreview(BugTreePanel.java:172)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.BugTreePanel.setPreviewEnabled(BugTreePanel.java:155)
	at org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel.setPreviewEnabled(ToolWindowPanel.java:237)
	at org.twodividedbyzero.idea.findbugs.actions.PreviewSelectBugInstance.setSelectedImpl(PreviewSelectBugInstance.java:70)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractToggleAction.setSelected(AbstractToggleAction.java:163)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:274)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
