### ISSUE TITLE
org.jetbrains.plugins.scala.util.UIFreezingGuard$UnfreezeException$: Long scala calculation on UI thread canceled

### ISSUE THREAD

**Issue by JavaJimFl** [andrepdo/findbugs-idea#287]
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2017.3.4
    IDEA-Build: IU-173.4548.28, January 29, 2018
    JRE: 1.8.0_152-release-1024-b11 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

Additional Infos
Trying to run a unit test.

java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy209.newBug(Unknown Source)
	at org.twodividedbyzero.idea.findbugs.messages.MessageBusManager.publishNewBug(MessageBusManager.java:81)
	at org.twodividedbyzero.idea.findbugs.core.Reporter$2.run(Reporter.java:145)
	at org.twodividedbyzero.idea.findbugs.core.Reporter$RunnableProcessor.process(Reporter.java:315)
	at org.twodividedbyzero.idea.findbugs.core.Reporter$RunnableProcessor.process(Reporter.java:312)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor585.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.twodividedbyzero.idea.findbugs.messages.MessageBus$1.invoke(MessageBus.java:80)
	... 25 more
Caused by: org.jetbrains.plugins.scala.util.UIFreezingGuard$UnfreezeException$: Long scala calculation on UI thread canceled

**Comment by JavaJimFl** [comment]
The project the plugin is trying to analyze is a mixed Scala/Java project.  I'm not seeing the same issue during a SonarQube analysis.

The plugin is also constantly analyzing the code.  If I save one file, all of them (in a very large project) are analyzed.
