### ISSUE TITLE
Could not create FindBugs-IDEA custom plugins directory: C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.6\plugins\FindBugs-IDEA-1.0.1\customPlugins

### ISSUE THREAD

**Issue by debbyzang** [andrepdo/findbugs-idea#310]
The error was copied to the clipboard. Press Ctrl+V
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2018.1.6
    IDEA-Build: IU-181.5540.7, July 11, 2018
    JRE: 1.8.0_152-release-1136-b39 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.lang.IllegalStateException: Could not create FindBugs-IDEA custom plugins directory: C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.6\plugins\FindBugs-IDEA-1.0.1\customPlugins
	at org.twodividedbyzero.idea.findbugs.plugins.Plugins.getDirectory(Plugins.java:102)
	at org.twodividedbyzero.idea.findbugs.plugins.Plugins.deploy(Plugins.java:110)
	at org.twodividedbyzero.idea.findbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:76)
	at org.twodividedbyzero.idea.findbugs.plugins.PluginLoader.load(PluginLoader.java:53)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:294)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:244)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:217)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$300(FindBugsStarter.java:73)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$3.run(FindBugsStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by debbyzang** [comment]
this caused by off-line installation
