### ISSUE TITLE
IllegalStateException: Could not create FindBugs-IDEA custom plugins directory

### ISSUE THREAD

**Issue by connect2manu** [andrepdo/findbugs-idea#332]
When user not a system admin and do not have access to create a file/folder under C:\Program Files\*. IMO this should be moved to %appdata% dir for windows installation.

Have same problem with IntelliJ 2017 and 2018 community versions.

Stacktrace:
java.lang.IllegalStateException: Could not create FindBugs-IDEA custom plugins directory: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.1\plugins\FindBugs-IDEA-1.0.1\customPlugins
	at org.twodividedbyzero.idea.findbugs.plugins.Plugins.getDirectory(Plugins.java:102)
	at org.twodividedbyzero.idea.findbugs.plugins.Plugins.deploy(Plugins.java:110)
	at org.twodividedbyzero.idea.findbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:76)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:303)
	at org.twodividedbyzero.idea.findbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:297)
	at org.twodividedbyzero.idea.findbugs.gui.settings.GeneralTab.reset(GeneralTab.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.SettingsPane.reset(SettingsPane.java:168)
	at org.twodividedbyzero.idea.findbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:93)
	at org.twodividedbyzero.idea.findbugs.gui.settings.ModuleConfigurableImpl.reset(ModuleConfigurableImpl.java:56)
	at com.intellij.openapi.roots.ui.configuration.ModuleConfigurableWrapper.reset(ModuleConfigurableWrapper.java:61)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:62)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.createPanel(ModuleEditor.java:253)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:264)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:117)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:89)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:619)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:196)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:610)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:228)
	at com.intellij.openapi.ui.MasterDetailsComponent.restoreLastSelection(MasterDetailsComponent.java:353)
	at com.intellij.openapi.ui.MasterDetailsComponent.reset(MasterDetailsComponent.java:335)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:247)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.reset(ModuleStructureConfigurable.java:353)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:354)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:59)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:81)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:96)
	at com.intellij.ide.actions.ShowStructureSettingsAction$1.<init>(ShowStructureSettingsAction.java:45)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:45)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by connect2manu** [comment]
Note that I've to disable FindBugs plugin in IntelliJ to prevent those annoying error messages.
