### ISSUE TITLE
DeprecatedMethodException thrown on start

### ISSUE THREAD

**Issue by itsTyrion** [andrepdo/findbugs-idea#437]
```
2019-11-02 14:49:50,895 [  11050]   WARN - util.DeprecatedMethodException - This method in class com.intellij.util.containers.SoftHashMap is deprecated and going to be removed soon. Use ContainerUtil.createSoftMap() instead 
com.intellij.util.DeprecatedMethodException: This method in class com.intellij.util.containers.SoftHashMap is deprecated and going to be removed soon. Use ContainerUtil.createSoftMap() instead
        at com.intellij.util.DeprecatedMethodException.report(DeprecatedMethodException.java:14)
        at com.intellij.util.containers.SoftHashMap.<init>(SoftHashMap.java:44)
        at org.twodividedbyzero.idea.findbugs.resources.ResourcesLoader.<clinit>(ResourcesLoader.java:57)
        at org.twodividedbyzero.idea.findbugs.gui.settings.GeneralTab.getSearchPath(GeneralTab.java:111)
        at org.twodividedbyzero.idea.findbugs.gui.settings.SearchableOptionContributorImpl.processOptions(SearchableOptionContributorImpl.java:39)
        at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:32)
        at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:74)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
        at com.intellij.openapi.application.Preloader.lambda$componentsInitialized$2(Preloader.java:71)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
(Printed to stdout when I started IDEA via idea.sh)

**Comment by planetf1** [comment]
++ I see the same in the log - was about to report too! So this extension is likely to break at some point
