### ISSUE TITLE
Findbugs not starting with EAP 2020 

### ISSUE THREAD

**Issue by Nerexis** [andrepdo/findbugs-idea#472]
The error was copied to the clipboard. Press Ctrl+V
Product Infos
    FindBugs: 3.0.1
    FindBugs-IDEA: FindBugs-IDEA 1.0.1
    IDEA: IntelliJ IDEA 2020.1 EAP
    IDEA-Build: IU-201.5259.13, February 12, 2020
    JRE: 11.0.6+8-b722.2 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin FindBugs-IDEA
	at com.intellij.serviceContainer.PlatformComponentManagerImplKt.handleComponentError(PlatformComponentManagerImpl.kt:847)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.kt:293)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:157)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:116)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion.registerComponents(projectLoader.kt:29)
	at com.intellij.openapi.project.ProjectLoadHelper.registerComponents(projectLoader.kt)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:312)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.convertAndLoadProject(PlatformProjectOpenProcessor.kt:416)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.prepareProject(PlatformProjectOpenProcessor.kt:312)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.access$prepareProject(PlatformProjectOpenProcessor.kt:1)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:183)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:58)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$$special$$inlined$createModalTask$1.run(progress.kt:37)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:931)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:481)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:75)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:626)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:571)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:245)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: While loading class org.twodividedbyzero.idea.findbugs.core.FindBugsCompileAfterHook: com/intellij/openapi/compiler/CompilationStatusListener [Plugin: FindBugs-IDEA] [Plugin: FindBugs-IDEA]
	... 27 more
Caused by: com.intellij.diagnostic.PluginException: While loading class org.twodividedbyzero.idea.findbugs.core.FindBugsCompileAfterHook: com/intellij/openapi/compiler/CompilationStatusListener [Plugin: FindBugs-IDEA]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponent(PlatformComponentManagerImpl.kt:248)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:153)
	... 24 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/compiler/CompilationStatusListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
	... 31 more
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.compiler.CompilationStatusListener PluginClassLoader[FindBugs-IDEA, 1.0.1] com.intellij.ide.plugins.cl.PluginClassLoader@40018d71
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 38 more

**Comment by vadakr** [comment]
Move to https://github.com/JetBrains/spotbugs-intellij-plugin

It isn't officially published as far I can see i.e. it doesn't show up in the search results in IntelliJ if you search for 'spotbugs'. But it is maintained by JetBrains employees because you can see the 'JB team' label on the project's github (see https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)

1. Clone it and run the intellij.buildPlugin Gradle task
2. The plugin JAR is generated in the build/distributions folder
3. Install it manually in IntelliJ (Plugins > click on the gear/cog icon and choose 'Install Plugin from disk')

BTW it also uses SpotBugs 4 which is a welcome upgrade from 3.1
