### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by igorky** [andrepdo/findbugs-idea#99]
null
java.lang.NullPointerException
	at org.twodividedbyzero.idea.findbugs.gui.tree.model.GroupTreeModel.findNodeByBugInstance(GroupTreeModel.java:290)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.findTreeNodeByBugInstance(BugTreeHelper.java:341)
	at org.twodividedbyzero.idea.findbugs.gui.tree.BugTreeHelper.gotoNode(BugTreeHelper.java:333)
	at org.twodividedbyzero.idea.findbugs.gui.tree.view.BugTree.gotoNode(BugTree.java:229)
	at org.twodividedbyzero.idea.findbugs.gui.editor.BugsLineMarkerProvider$BugGutterIconNavigationHandler.navigate(BugsLineMarkerProvider.java:171)
	at com.intellij.codeInsight.daemon.LineMarkerInfo$NavigateAction.actionPerformed(LineMarkerInfo.java:123)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1340)
	at com.intellij.openapi.editor.impl.EditorImpl.processMouseReleased(EditorImpl.java:4085)
	at com.intellij.openapi.editor.impl.EditorImpl.access$11100(EditorImpl.java:128)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter$2.run(EditorImpl.java:5670)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:5673)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5563)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by retomerz** [comment]
Will be fixed in 0.9.997

**Comment by retomerz** [comment]
Fixed in version 0.9.997
